#Requires -Version 5.1
<#
.SYNOPSIS
    End-to-end smoke test: runs the full Invoke-Main orchestration against a fully stubbed
    Active Directory, with no RSAT present, and asserts a report + CSV bundle is produced.
.DESCRIPTION
    Every AD cmdlet the orchestration touches is replaced with an in-memory stub, and
    Import-Module is shadowed with a no-op, so the real pipeline (collection -> CSV -> HTML)
    executes on any host. Verifies wiring, output paths, HTML/CSV emission and the roll-up.
#>
[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
$fail = 0
function Check($cond, $name) {
    if ($cond) { Write-Host "  [PASS] $name" -ForegroundColor Green }
    else { Write-Host "  [FAIL] $name" -ForegroundColor Red; $script:fail++ }
}

$target = Join-Path (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) 'src/ADForestAssessment/Invoke-ADForestAssessment.ps1'
$env:ADFA_NO_AUTORUN = '1'
. $target

# ---- Stub RSAT + AD cmdlets -------------------------------------------------
function Import-Module { param([Parameter(ValueFromRemainingArguments)]$args) }
function Start-Transcript { param([Parameter(ValueFromRemainingArguments)]$args) }
function Stop-Transcript { param([Parameter(ValueFromRemainingArguments)]$args) }

$now = Get-Date
function Get-ADForest { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='contoso.com'; RootDomain='contoso.com'; ForestMode='Windows2016Forest'
        Domains=@('contoso.com'); Sites=@('Default-First-Site-Name'); GlobalCatalogs=@('dc1.contoso.com')
        SchemaMaster='dc1.contoso.com'; DomainNamingMaster='dc1.contoso.com'; UPNSuffixes=@() } }
function Get-ADDomain { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ DNSRoot='contoso.com'; NetBIOSName='CONTOSO'; DomainMode='Windows2016Domain'
        PDCEmulator='dc1.contoso.com'; RIDMaster='dc1.contoso.com'; InfrastructureMaster='dc1.contoso.com'
        DomainSID=[pscustomobject]@{ Value='S-1-5-21-1-2-3' }; DistinguishedName='DC=contoso,DC=com' } }
function Get-ADDomainController { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ HostName='dc1.contoso.com'; Name='DC1'; Site='Default-First-Site-Name'
        IPv4Address='10.0.0.1'; IsGlobalCatalog=$true; IsReadOnly=$false; ComputerObjectDN='CN=DC1,OU=DCs,DC=contoso,DC=com' } }
function Get-ADComputer { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ OperatingSystem='Windows Server 2019'; OperatingSystemVersion='10.0'; Enabled=$true; whenCreated=$now } }
function Get-ADReplicationPartnerMetadata { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Partner='dc2.contoso.com'; ConsecutiveReplicationFailures=0; LastReplicationSuccess=$now } }
function Get-ADReplicationFailure { param([Parameter(ValueFromRemainingArguments)]$a) @() }
function Get-ADReplicationQueueOperation { param([Parameter(ValueFromRemainingArguments)]$a) @() }
function Get-ADReplicationSite { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='Default-First-Site-Name'; Description=''; WhenCreated=$now; WhenChanged=$now } }
function Get-ADReplicationSubnet { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='10.0.0.0/24'; Site='Default-First-Site-Name'; Location=''; Description='' } }
function Get-ADReplicationSiteLink { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='DEFAULTIPSITELINK'; Cost=100; ReplicationFrequencyInMinutes=180
        InterSiteTransportProtocol='IP'; SitesIncluded=@('CN=Default-First-Site-Name') } }
function Get-ADReplicationConnection { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='conn1'; FromServer='dc2'; ToServer='dc1'; Enabled=$true; AutoGenerated=$true } }
function Get-ADTrust { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='fabrikam.com'; Source='contoso.com'; Target='fabrikam.com'; Direction='Bidirectional'
        TrustType='Forest'; IntraForest=$false; ForestTransitive=$true; SelectiveAuthentication=$false
        SIDFilteringForestAware=$false; SIDFilteringQuarantined=$true; TGTDelegation=$false
        UsesRC4Encryption=$false; Created=$now; Modified=$now } }
function Get-ADDefaultDomainPasswordPolicy { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ MinPasswordLength=8; PasswordHistoryCount=24; MaxPasswordAge=[timespan]::FromDays(42)
        MinPasswordAge=[timespan]::FromDays(1); ComplexityEnabled=$true; LockoutThreshold=5; ReversibleEncryptionEnabled=$false } }
function Get-ADFineGrainedPasswordPolicy { param([Parameter(ValueFromRemainingArguments)]$a) @() }
function Get-ADGroupMember { param([Parameter(ValueFromRemainingArguments)]$a)
    1..3 | ForEach-Object { [pscustomobject]@{ SamAccountName="admin$_" } } }
function Get-ADUser { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ PasswordLastSet=$now.AddDays(-30); SamAccountName='krbtgt' } }
function Get-ADOptionalFeature { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='Recycle Bin Feature'; EnabledScopes=@('CN=Partitions') } }
function Get-ADRootDSE { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ configurationNamingContext='CN=Configuration,DC=contoso,DC=com'; schemaNamingContext='CN=Schema,CN=Configuration,DC=contoso,DC=com' } }
function Get-ADObject { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ tombstoneLifetime=180; 'ms-DS-MachineAccountQuota'=0; rangeUpper=15334; whenChanged=$now } }
# No verification tools on this host -> trust health should degrade to Not Assessed honestly.
function Test-CommandAvailable { param([string]$Name) return $false }
function Test-ModuleAvailable { param([string]$Name) return $false }
function Test-TcpPort { param([string]$ComputerName, [int]$Port, [int]$TimeoutMs) return $true }

$out = Join-Path ([IO.Path]::GetTempPath()) ("adfa_smoke_" + [guid]::NewGuid().ToString('N'))
$script:OutputPath = $out
$script:Sections = @('All')
$script:AllDomains = $false
$script:IncludeDcdiag = $false
$script:IncludeRepadmin = $false
$script:SkipTrustVerification = $false
$script:Server = $null
$script:Credential = $null

Write-Host "== Running Invoke-Main against stubbed AD ==" -ForegroundColor Cyan
$result = Invoke-Main

Check ($null -ne $result) 'Invoke-Main returned a summary object'
Check (Test-Path $result.ReportPath) 'HTML report written'
Check (Test-Path $result.CsvPath) 'CSV folder created'
$csvs = @(Get-ChildItem -Path $result.CsvPath -Filter *.csv)
Check ($csvs.Count -ge 8) ("CSV bundle populated ({0} files)" -f $csvs.Count)
$html = Get-Content $result.ReportPath -Raw
Check ($html -match 'Active Directory Forest Assessment') 'Report has title'
Check ($html -match 'Trusts &amp; Two-Way Health' -or $html -match 'Trusts') 'Report includes trust section'
Check ($html -match "class='b-ok'") 'Report renders roll-up badges'
$trustCsv = Join-Path $result.CsvPath 'Trusts & Two-Way Health.csv'
if (Test-Path $trustCsv) {
    $trow = Import-Csv $trustCsv | Select-Object -First 1
    Check ($trow.Health -eq 'Not Assessed') 'Trust health honestly Not Assessed when no verify tools present'
} else {
    Check $false 'Trust CSV exists'
}
Check ($result.Summary.Pass -ge 1) 'Roll-up counted at least one Pass'

# Detailed log + consolidated findings.
Check (Test-Path $result.LogFile) 'Detailed assessment log written'
if (Test-Path $result.LogFile) {
    $log = Get-Content $result.LogFile -Raw
    Check ($log -match '\[RESULT\]' -and $log -match 'Summary: Pass=') 'Log contains itemised results and summary line'
    Check ($log -match '\[STAGE') 'Log contains stage entries'
}
Check (Test-Path $result.FindingsFile) 'Consolidated findings CSV written'
if (Test-Path $result.FindingsFile) {
    $fnd = Import-Csv $result.FindingsFile
    Check ((@($fnd)[0].PSObject.Properties.Name -contains 'Section') -and (@($fnd)[0].PSObject.Properties.Name -contains 'Status')) 'Findings CSV has Section+Status columns'
}

# Full identity export produced per-domain CSVs with flattened attributes.
$usersCsv = Get-ChildItem -Path $result.CsvPath -Filter 'AllUsers_*.csv' -ErrorAction SilentlyContinue
$compCsv = Get-ChildItem -Path $result.CsvPath -Filter 'AllComputers_*.csv' -ErrorAction SilentlyContinue
Check (@($usersCsv).Count -ge 1) 'Full user export CSV written (AllUsers_*.csv)'
Check (@($compCsv).Count -ge 1) 'Full computer export CSV written (AllComputers_*.csv)'

# DC diagnostics now carry an overall Status + Failures column.
$dcCsv = Join-Path $result.CsvPath 'DC Diagnostics.csv'
if (Test-Path $dcCsv) {
    $dcRow = Import-Csv $dcCsv | Select-Object -First 1
    Check ($dcRow.PSObject.Properties.Name -contains 'Status') 'DC Diagnostics has overall Status column'
    Check ($dcRow.PSObject.Properties.Name -contains 'Failures') 'DC Diagnostics has Failures detail column'
}
else { Check $false 'DC Diagnostics CSV exists' }

# Replication now carries a FailureDetail column for the exact failing partner/error.
$repCsv = Join-Path $result.CsvPath 'Replication Health.csv'
if (Test-Path $repCsv) {
    $repRow = Import-Csv $repCsv | Select-Object -First 1
    Check ($repRow.PSObject.Properties.Name -contains 'FailureDetail') 'Replication Health has FailureDetail column'
}
else { Check $false 'Replication Health CSV exists' }

Write-Host ""
Write-Host ("Output bundle: {0}" -f $result.OutputRoot)
Get-ChildItem -Recurse $result.OutputRoot | Select-Object -First 30 FullName | ForEach-Object { Write-Host ("   {0}" -f $_.FullName) }

# cleanup
Remove-Item -Recurse -Force $out -ErrorAction SilentlyContinue
Remove-Item Env:\ADFA_NO_AUTORUN -ErrorAction SilentlyContinue
Write-Host ""
if ($fail -gt 0) { Write-Host "SMOKE TEST FAILED ($fail)" -ForegroundColor Red; exit 1 }
Write-Host "SMOKE TEST PASSED" -ForegroundColor Green
exit 0
