#Requires -Version 5.1
<#
.SYNOPSIS
    End-to-end smoke test: runs the full Invoke-Main orchestration against a fully stubbed
    Active Directory, with no RSAT present, and asserts a report + CSV bundle is produced.
.DESCRIPTION
    Every AD cmdlet the orchestration touches is replaced with an in-memory stub, and
    Import-Module is shadowed with a no-op, so the real pipeline (collection -> CSV -> HTML)
    executes on any host. Verifies wiring, output paths, HTML/CSV emission and the roll-up.
#>
[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
$fail = 0
function Check($cond, $name) {
    if ($cond) { Write-Host "  [PASS] $name" -ForegroundColor Green }
    else { Write-Host "  [FAIL] $name" -ForegroundColor Red; $script:fail++ }
}

$target = Join-Path (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) 'src/ADForestAssessment/Invoke-ADForestAssessment.ps1'
$env:ADFA_NO_AUTORUN = '1'
. $target

# ---- Stub RSAT + AD cmdlets -------------------------------------------------
function Import-Module { param([Parameter(ValueFromRemainingArguments)]$args) }
function Start-Transcript { param([Parameter(ValueFromRemainingArguments)]$args) }
function Stop-Transcript { param([Parameter(ValueFromRemainingArguments)]$args) }

$now = Get-Date

# Get-ADDomain returns DomainSID as a System.Security.Principal.SecurityIdentifier, whose
# ToString() is the SID string. The collector reads it two ways - [string]$d.DomainSID at
# Get-AdfaDomainSummary, and .DomainSID.Value elsewhere - so the stub must honour both.
# A bare [pscustomobject]@{Value=...} honours only .Value: its ToString() yields
# "@{Value=S-1-5-21-1-2-3}", which the JSON guard caught being written into the report.
# SecurityIdentifier itself cannot be constructed off Windows, and this harness must run
# anywhere, so ToString() is overridden instead.
function New-StubSid {
    param([string]$Sid)
    $o = [pscustomobject]@{ Value = $Sid }
    $o | Add-Member -MemberType ScriptMethod -Name ToString -Value { $this.Value } -Force
    return $o
}
function Get-ADForest { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='contoso.com'; RootDomain='contoso.com'; ForestMode='Windows2016Forest'
        Domains=@('contoso.com'); Sites=@('Default-First-Site-Name'); GlobalCatalogs=@('dc1.contoso.com')
        SchemaMaster='dc1.contoso.com'; DomainNamingMaster='dc1.contoso.com'; UPNSuffixes=@() } }
function Get-ADDomain { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ DNSRoot='contoso.com'; NetBIOSName='CONTOSO'; DomainMode='Windows2016Domain'
        PDCEmulator='dc1.contoso.com'; RIDMaster='dc1.contoso.com'; InfrastructureMaster='dc1.contoso.com'
        DomainSID=(New-StubSid 'S-1-5-21-1-2-3'); DistinguishedName='DC=contoso,DC=com' } }
function Get-ADDomainController { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ HostName='dc1.contoso.com'; Name='DC1'; Site='Default-First-Site-Name'
        IPv4Address='10.0.0.1'; IsGlobalCatalog=$true; IsReadOnly=$false; ComputerObjectDN='CN=DC1,OU=DCs,DC=contoso,DC=com' } }
function Get-ADComputer { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ OperatingSystem='Windows Server 2019'; OperatingSystemVersion='10.0'; Enabled=$true; whenCreated=$now } }
function Get-ADReplicationPartnerMetadata { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Partner='dc2.contoso.com'; ConsecutiveReplicationFailures=0; LastReplicationSuccess=$now } }
function Get-ADReplicationFailure { param([Parameter(ValueFromRemainingArguments)]$a) @() }
function Get-ADReplicationQueueOperation { param([Parameter(ValueFromRemainingArguments)]$a) @() }
function Get-ADReplicationSite { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='Default-First-Site-Name'; Description=''; WhenCreated=$now; WhenChanged=$now } }
function Get-ADReplicationSubnet { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='10.0.0.0/24'; Site='Default-First-Site-Name'; Location=''; Description='' } }
function Get-ADReplicationSiteLink { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='DEFAULTIPSITELINK'; Cost=100; ReplicationFrequencyInMinutes=180
        InterSiteTransportProtocol='IP'; SitesIncluded=@('CN=Default-First-Site-Name') } }
function Get-ADReplicationConnection { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='conn1'; FromServer='dc2'; ToServer='dc1'; Enabled=$true; AutoGenerated=$true } }
function Get-ADTrust { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='fabrikam.com'; Source='contoso.com'; Target='fabrikam.com'; Direction='Bidirectional'
        TrustType='Forest'; IntraForest=$false; ForestTransitive=$true; SelectiveAuthentication=$false
        SIDFilteringForestAware=$false; SIDFilteringQuarantined=$true; TGTDelegation=$false
        UsesRC4Encryption=$false; Created=$now; Modified=$now } }
function Get-ADDefaultDomainPasswordPolicy { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ MinPasswordLength=8; PasswordHistoryCount=24; MaxPasswordAge=[timespan]::FromDays(42)
        MinPasswordAge=[timespan]::FromDays(1); ComplexityEnabled=$true; LockoutThreshold=5; ReversibleEncryptionEnabled=$false } }
function Get-ADFineGrainedPasswordPolicy { param([Parameter(ValueFromRemainingArguments)]$a) @() }
function Get-ADGroupMember { param([Parameter(ValueFromRemainingArguments)]$a)
    1..3 | ForEach-Object { [pscustomobject]@{ SamAccountName="admin$_" } } }
function Get-ADUser { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ PasswordLastSet=$now.AddDays(-30); SamAccountName='krbtgt' } }
function Get-ADOptionalFeature { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='Recycle Bin Feature'; EnabledScopes=@('CN=Partitions') } }
function Get-ADRootDSE { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ configurationNamingContext='CN=Configuration,DC=contoso,DC=com'; schemaNamingContext='CN=Schema,CN=Configuration,DC=contoso,DC=com' } }
function Get-ADObject { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ tombstoneLifetime=180; 'ms-DS-MachineAccountQuota'=0; rangeUpper=15334; whenChanged=$now } }
# No verification tools on this host -> trust health should degrade to Not Assessed honestly.
function Test-CommandAvailable { param([string]$Name) return $false }
function Test-ModuleAvailable { param([string]$Name) return $false }
function Test-TcpPort { param([string]$ComputerName, [int]$Port, [int]$TimeoutMs) return $true }

$out = Join-Path ([IO.Path]::GetTempPath()) ("adfa_smoke_" + [guid]::NewGuid().ToString('N'))
$script:OutputPath = $out
$script:Sections = @('All')
$script:AllDomains = $false
$script:IncludeDcdiag = $false
$script:IncludeRepadmin = $false
$script:SkipTrustVerification = $false
$script:Server = $null
$script:Credential = $null

Write-Host "== Running Invoke-Main against stubbed AD ==" -ForegroundColor Cyan
$result = Invoke-Main

Check ($null -ne $result) 'Invoke-Main returned a summary object'
Check (Test-Path $result.ReportPath) 'HTML report written'
Check (Test-Path $result.CsvPath) 'CSV folder created'
$csvs = @(Get-ChildItem -Path $result.CsvPath -Filter *.csv)
Check ($csvs.Count -ge 8) ("CSV bundle populated ({0} files)" -f $csvs.Count)
$html = Get-Content $result.ReportPath -Raw
Check ($html -match 'Active Directory Forest Assessment') 'Report has title'
Check ($html -match 'Trusts &amp; Two-Way Health' -or $html -match 'Trusts') 'Report includes trust section'
Check ($html -match "class='b-ok'") 'Report renders roll-up badges'
$trustCsv = Join-Path $result.CsvPath 'Trusts & Two-Way Health.csv'
if (Test-Path $trustCsv) {
    $trow = Import-Csv $trustCsv | Select-Object -First 1
    Check ($trow.Health -eq 'Not Assessed') 'Trust health honestly Not Assessed when no verify tools present'
} else {
    Check $false 'Trust CSV exists'
}
Check ($result.Summary.Pass -ge 1) 'Roll-up counted at least one Pass'

# Detailed log + consolidated findings.
Check (Test-Path $result.LogFile) 'Detailed assessment log written'
if (Test-Path $result.LogFile) {
    $log = Get-Content $result.LogFile -Raw
    Check ($log -match '\[RESULT\]' -and $log -match 'Summary: Pass=') 'Log contains itemised results and summary line'
    Check ($log -match '\[STAGE') 'Log contains stage entries'
}
Check (Test-Path $result.FindingsFile) 'Consolidated findings CSV written'
if (Test-Path $result.FindingsFile) {
    $fnd = Import-Csv $result.FindingsFile
    Check ((@($fnd)[0].PSObject.Properties.Name -contains 'Section') -and (@($fnd)[0].PSObject.Properties.Name -contains 'Status')) 'Findings CSV has Section+Status columns'
}

# Full identity export produced per-domain CSVs with flattened attributes.
$usersCsv = Get-ChildItem -Path $result.CsvPath -Filter 'AllUsers_*.csv' -ErrorAction SilentlyContinue
$compCsv = Get-ChildItem -Path $result.CsvPath -Filter 'AllComputers_*.csv' -ErrorAction SilentlyContinue
Check (@($usersCsv).Count -ge 1) 'Full user export CSV written (AllUsers_*.csv)'
Check (@($compCsv).Count -ge 1) 'Full computer export CSV written (AllComputers_*.csv)'

# DC diagnostics now carry an overall Status + Failures column.
$dcCsv = Join-Path $result.CsvPath 'DC Diagnostics.csv'
if (Test-Path $dcCsv) {
    $dcRow = Import-Csv $dcCsv | Select-Object -First 1
    Check ($dcRow.PSObject.Properties.Name -contains 'Status') 'DC Diagnostics has overall Status column'
    Check ($dcRow.PSObject.Properties.Name -contains 'Failures') 'DC Diagnostics has Failures detail column'
}
else { Check $false 'DC Diagnostics CSV exists' }

# Replication now carries a FailureDetail column for the exact failing partner/error.
$repCsv = Join-Path $result.CsvPath 'Replication Health.csv'
if (Test-Path $repCsv) {
    $repRow = Import-Csv $repCsv | Select-Object -First 1
    Check ($repRow.PSObject.Properties.Name -contains 'FailureDetail') 'Replication Health has FailureDetail column'
}
else { Check $false 'Replication Health CSV exists' }

Write-Host ""
Write-Host ("Output bundle: {0}" -f $result.OutputRoot)
Get-ChildItem -Recurse $result.OutputRoot | Select-Object -First 30 FullName | ForEach-Object { Write-Host ("   {0}" -f $_.FullName) }

# =============================================================================
# MULTI-DOMAIN PASS (regression: live run 2026-08-31)
# =============================================================================
# The single-domain pass above cannot catch aggregation faults. Per-domain sections are
# built as `$rows = foreach ($d in $targetDomains) { Get-AdfaSomething -DomainName $d }`.
# While collectors ended in `return , @($rows)` each iteration emitted the array as ONE
# object, so with MORE THAN ONE domain the section became an array of arrays. Every
# consumer then looked for a Status property on an array, found none, and skipped it -
# twelve sections were collected and silently discarded, DNS-vs-AD consistency and DC
# secure channel among them. One domain hid it completely.
Write-Host ""
Write-Host "== Running Invoke-Main against a THREE-DOMAIN stubbed forest ==" -ForegroundColor Cyan

$multiDomains = @('contoso.com', 'north.contoso.com', 'epal.contoso.com')
function Get-ADForest { param([Parameter(ValueFromRemainingArguments)]$a)
    [pscustomobject]@{ Name='contoso.com'; RootDomain='contoso.com'; ForestMode='Windows2016Forest'
        Domains=@('contoso.com','north.contoso.com','epal.contoso.com')
        Sites=@('Default-First-Site-Name'); GlobalCatalogs=@('dc1.contoso.com')
        SchemaMaster='dc1.contoso.com'; DomainNamingMaster='dc1.contoso.com'; UPNSuffixes=@() } }

$out2 = Join-Path ([IO.Path]::GetTempPath()) ("adfa_smoke_multi_" + [guid]::NewGuid().ToString('N'))
$script:OutputPath = $out2
$script:AllDomains = $true
$result2 = Invoke-Main

Check ($null -ne $result2) 'Multi-domain: Invoke-Main returned a summary object'
Check (@($result2.DomainsScoped).Count -eq 3) ("Multi-domain: three domains scoped ({0})" -f @($result2.DomainsScoped).Count)

# The core assertion: per-domain sections must contribute findings, not vanish.
$findings2 = @(Import-Csv (Join-Path $result2.CsvPath 'Findings-Consolidated.csv'))
Check ($findings2.Count -gt 0) ("Multi-domain: consolidated findings are not empty ({0} rows)" -f $findings2.Count)

foreach ($sec in @('Password Policy', 'Security Posture', 'DNS vs AD Consistency', 'DC Secure Channel & Machine Passwords')) {
    $n = @($findings2 | Where-Object { $_.Section -eq $sec }).Count
    Check ($n -gt 0) ("Multi-domain: section '{0}' reached the consolidated findings ({1} rows)" -f $sec, $n)
}

# Every scoped domain must actually appear - not just the first one.
$scopes = @($findings2 | Select-Object -ExpandProperty Scope -Unique | Where-Object { $_ })
foreach ($d in $multiDomains) {
    Check ($scopes -contains $d) ("Multi-domain: findings carry scope '{0}'" -f $d)
}

# A section CSV must hold real columns, never array metadata (Length/Rank/Count).
$ppCsv = Join-Path $result2.CsvPath 'Password Policy.csv'
if (Test-Path $ppCsv) {
    $cols = @((Import-Csv $ppCsv | Select-Object -First 1).PSObject.Properties.Name)
    Check (-not ($cols -contains 'Length' -and $cols -contains 'Rank')) ("Multi-domain: section CSV holds findings, not array metadata ({0})" -f ($cols -join ','))
}
else { Check $false 'Multi-domain: Password Policy CSV exists' }

# The reconciliation file must exist and show no unexplained empty status-bearing section.
$auditCsv = Join-Path $result2.CsvPath 'Section-Coverage.csv'
Check (Test-Path $auditCsv) 'Multi-domain: Section-Coverage.csv written'
if (Test-Path $auditCsv) {
    $audit = @(Import-Csv $auditCsv)
    Check ($audit.Count -gt 0) ("Multi-domain: reconciliation covers {0} sections" -f $audit.Count)
    $lost = @($audit | Where-Object { $_.Section -eq 'DNS vs AD Consistency' -and [int]$_.FindingsReported -eq 0 })
    Check ($lost.Count -eq 0) 'Multi-domain: DNS vs AD Consistency reported findings (reconciliation)'
}

# ---- JSON report (machine-readable twin of the HTML) -----------------------
# A phased rollout re-runs the assessment between phases and diffs the result, so the JSON
# must carry the findings and the section data in full. The depth check matters: ConvertTo-Json
# defaults to depth 2, which would render section rows as "System.Object[]" instead of values.
Check (-not [string]::IsNullOrWhiteSpace($result2.JsonPath)) 'Multi-domain: JsonPath returned'
Check (Test-Path $result2.JsonPath) 'Multi-domain: Assessment.json written'
if (Test-Path $result2.JsonPath) {
    $doc = Get-Content $result2.JsonPath -Raw | ConvertFrom-Json
    Check ($doc.schemaVersion -eq 1) 'JSON: schemaVersion present'
    Check ($doc.tool.name -eq 'ADForestAssessment') 'JSON: tool name present'
    Check (-not [string]::IsNullOrWhiteSpace([string]$doc.tool.version)) 'JSON: tool version present'
    Check ($doc.run.forest -eq 'contoso.com') 'JSON: run.forest recorded'
    Check (@($doc.run.domainsScoped).Count -eq 3) ("JSON: all three domains recorded ({0})" -f @($doc.run.domainsScoped).Count)

    # The JSON summary and the CSV findings must describe the same run.
    $jf = @($doc.findings)
    Check ($jf.Count -eq @($findings2).Count) ("JSON: findings match the consolidated CSV ({0} vs {1})" -f $jf.Count, @($findings2).Count)
    Check (@($doc.coverage).Count -eq $audit.Count) ("JSON: coverage matches Section-Coverage.csv ({0})" -f @($doc.coverage).Count)
    # Every finding must land in exactly one bucket. 'Info' is a valid New-Finding status that
    # the four legacy counters do not match, so the document adds it plus an 'unclassified'
    # catch-all; without them 17 of 123 rows were counted nowhere.
    $jsonTotal = [int]$doc.summary.pass + [int]$doc.summary.warning + [int]$doc.summary.fail +
        [int]$doc.summary.notAssessed + [int]$doc.summary.info + [int]$doc.summary.unclassified
    Check ($jsonTotal -eq $jf.Count) ("JSON: summary buckets reconcile with findings ({0} = {1})" -f $jsonTotal, $jf.Count)
    Check ([int]$doc.summary.total -eq $jf.Count) ("JSON: summary.total matches findings ({0})" -f [int]$doc.summary.total)
    Check ([int]$doc.summary.info -gt 0) ("JSON: Info findings are counted, not invisible ({0})" -f [int]$doc.summary.info)
    Check ([int]$doc.summary.unclassified -eq 0) ("JSON: no finding escaped every bucket ({0})" -f [int]$doc.summary.unclassified)

    # Findings must carry the remediation guidance, not just the verdict.
    $fnames = @(@($jf)[0].PSObject.Properties.Name)
    Check ($fnames -contains 'Status' -and $fnames -contains 'Recommendation') ("JSON: findings carry Status + Recommendation ({0})" -f ($fnames -join ','))

    # Depth: a section's rows must be objects with real values, never a type name.
    $secNames = @($doc.sections.PSObject.Properties.Name)
    Check ($secNames.Count -gt 0) ("JSON: {0} sections serialised" -f $secNames.Count)
    Check ($secNames -contains 'DNS vs AD Consistency') 'JSON: recovery section present in sections map'
    # Depth truncation does NOT show up as "System.Object[]" - ConvertTo-Json stringifies the
    # row to PowerShell's hashtable form instead, e.g. '@{Scope=contoso.com; PolicyName=...}'.
    # Measured: at the ConvertTo-Json default of -Depth 2, every section row collapses to one
    # such string while `findings` (one level shallower) still serialises correctly. So the
    # guard asserts the rows are objects with readable properties, not that a type name is
    # absent - and it targets `sections`, which is the deepest branch.
    $raw = Get-Content $result2.JsonPath -Raw
    Check ($raw -notmatch '"@\{') 'JSON: no row collapsed to a hashtable string (depth sufficient)'

    $pp = @($doc.sections.'Password Policy')
    Check ($pp.Count -eq 3) ("JSON: Password Policy carries 3 rows ({0})" -f $pp.Count)
    Check (-not ($pp[0] -is [string])) 'JSON: section row is an object, not a stringified hashtable'
    Check ($null -ne $pp[0].PSObject.Properties['MinPasswordLength']) 'JSON: section row properties are addressable'
    Check ([string]$pp[0].Scope -eq 'contoso.com') ("JSON: section row value readable (Scope={0})" -f [string]$pp[0].Scope)
}

Write-Host ""
Write-Host ("Multi-domain bundle: {0}" -f $result2.OutputRoot)

# ---- Scenario 3: collection failures must be reported, never swallowed -------
# Regression guard for the empty-catch fixes. The failure mode being pinned is the one this
# repo already shipped once (v1.6.0): a collector throws, its rows quietly do not appear, and
# the report looks complete. Here the DC enumeration and the per-domain lookups all fail, and
# the run must come back saying so rather than looking clean.
Write-Host ""
Write-Host "== Running Invoke-Main with failing collectors ==" -ForegroundColor Cyan

# Get-ADDomain is deliberately NOT broken here: Invoke-Main calls it unguarded while resolving
# which domains to scope, long before any section runs, so breaking it aborts the run instead of
# exercising a catch. That unguarded path is recorded as PORT-PLAN H9 rather than widened into
# this change. The two collectors below are stubbed at the seam this change actually touches.
function Get-ADDomainController { param([Parameter(ValueFromRemainingArguments)]$a) throw 'STUB: ADWS unreachable on the target DC' }
function Get-ADFineGrainedPasswordPolicy { param([Parameter(ValueFromRemainingArguments)]$a) throw 'STUB: FGPP query denied' }
function Get-AdfaDomainSummary { param([Parameter(ValueFromRemainingArguments)]$a) throw 'STUB: domain summary unavailable' }
function Get-AdfaFsmoRole { param([Parameter(ValueFromRemainingArguments)]$a) throw 'STUB: FSMO lookup denied' }

$out3 = Join-Path ([IO.Path]::GetTempPath()) ("adfa_smoke_fail_" + [guid]::NewGuid().ToString('N'))
$script:OutputPath = $out3
$script:AllDomains = $false
$result3 = Invoke-Main

Check ($null -ne $result3) 'Failure mode: Invoke-Main still returns a summary rather than dying'
Check (Test-Path $result3.FindingsFile) 'Failure mode: consolidated findings still written'
$findings3 = @(Import-Csv $result3.FindingsFile)
Check ($findings3.Count -gt 0) ("Failure mode: findings are not empty ({0} rows)" -f $findings3.Count)

# Nothing may be reported as healthy on the strength of a collector that threw.
$dcEnum = @($findings3 | Where-Object { $_.Item -match 'Domain controller enumeration' })
Check ($dcEnum.Count -ge 1) 'Failure mode: DC enumeration failure is a first-class finding'
if ($dcEnum.Count -ge 1) {
    Check ($dcEnum[0].Status -eq 'Not Assessed') ("Failure mode: DC enumeration reported Not Assessed (got '{0}')" -f $dcEnum[0].Status)
    Check ($dcEnum[0].Detail -match 'ADWS unreachable') 'Failure mode: the underlying cause is carried into the report'
    Check ($dcEnum[0].Detail -match 'UNASSESSED, not clean') 'Failure mode: the finding refuses to imply the per-DC checks are clean'
}

$dsRow = @($findings3 | Where-Object { $_.Item -match 'Domain summary' })
Check ($dsRow.Count -ge 1) 'Failure mode: a domain whose summary failed appears as a row, not a gap'
if ($dsRow.Count -ge 1) { Check ($dsRow[0].Status -eq 'Not Assessed') 'Failure mode: failed domain summary is Not Assessed' }

$fsmoRow = @($findings3 | Where-Object { $_.Item -match 'FSMO roles' })
Check ($fsmoRow.Count -ge 1) 'Failure mode: a domain whose FSMO lookup failed appears as a row'
if ($fsmoRow.Count -ge 1) { Check ($fsmoRow[0].Status -eq 'Not Assessed') 'Failure mode: failed FSMO lookup is Not Assessed' }

$fgpp = @($findings3 | Where-Object { $_.Item -match 'Fine-grained password policies' })
Check ($fgpp.Count -ge 1) 'Failure mode: a failed FGPP query is reported, not indistinguishable from "none exist"'
if ($fgpp.Count -ge 1) {
    Check ($fgpp[0].Status -eq 'Not Assessed') 'Failure mode: failed FGPP query is Not Assessed'
    Check ($fgpp[0].Detail -match "NOT the same as") 'Failure mode: FGPP row states that absence was not measured'
}

# Non-vacuity: the run must not have passed simply because nothing was assessed at all.
$notAssessed3 = @($findings3 | Where-Object { $_.Status -eq 'Not Assessed' }).Count
Check ($notAssessed3 -ge 4) ("Failure mode: non-vacuity - {0} Not Assessed findings actually present" -f $notAssessed3)
# And crucially: no section may claim a Pass for something that could not be measured.
$falsePass = @($findings3 | Where-Object { $_.Status -eq 'Pass' -and $_.Detail -match 'could not|failed|unreachable' })
Check ($falsePass.Count -eq 0) ("Failure mode: nothing reports Pass off the back of a failure ({0})" -f $falsePass.Count)

# The JSON must reflect the same story, so a machine-readable consumer is not misled either.
if (Test-Path $result3.JsonPath) {
    $doc3 = Get-Content $result3.JsonPath -Raw | ConvertFrom-Json
    Check ([int]$doc3.summary.notAssessed -ge 4) ("Failure mode: JSON summary records the unassessed count ({0})" -f [int]$doc3.summary.notAssessed)
}
else { Check $false 'Failure mode: Assessment.json written' }

Remove-Item -Recurse -Force $out3 -ErrorAction SilentlyContinue

# cleanup
Remove-Item -Recurse -Force $out2 -ErrorAction SilentlyContinue
Remove-Item -Recurse -Force $out -ErrorAction SilentlyContinue
Remove-Item Env:\ADFA_NO_AUTORUN -ErrorAction SilentlyContinue
Write-Host ""
if ($fail -gt 0) { Write-Host "SMOKE TEST FAILED ($fail)" -ForegroundColor Red; exit 1 }
Write-Host "SMOKE TEST PASSED" -ForegroundColor Green
exit 0
